version: '3'

services:
    db:
        image: "microsoft/mssql-server-linux"
        ports: 
            - "1433:1433"
        environment:
            MSSQL_SA_PASSWORD: "Pass@word"
            ACCEPT_EULA: "Y"